// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deepdata.proto

package dg.model;

public final class Deepdata {
    private Deepdata() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code dg.model.CutboardType}
     */
    public enum CutboardType
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>CUTBOARD_TYPE_UNKNOWN = 0;</code>
         */
        CUTBOARD_TYPE_UNKNOWN(0),
        /**
         * <code>CUTBOARD_TYPE_VEHICLE = 1;</code>
         */
        CUTBOARD_TYPE_VEHICLE(1),
        /**
         * <code>CUTBOARD_TYPE_SYMBOL = 2;</code>
         */
        CUTBOARD_TYPE_SYMBOL(2),
        /**
         * <code>CUTBOARD_TYPE_PLATE = 3;</code>
         */
        CUTBOARD_TYPE_PLATE(3),
        UNRECOGNIZED(-1),;

        /**
         * <code>CUTBOARD_TYPE_UNKNOWN = 0;</code>
         */
        public static final int CUTBOARD_TYPE_UNKNOWN_VALUE = 0;
        /**
         * <code>CUTBOARD_TYPE_VEHICLE = 1;</code>
         */
        public static final int CUTBOARD_TYPE_VEHICLE_VALUE = 1;
        /**
         * <code>CUTBOARD_TYPE_SYMBOL = 2;</code>
         */
        public static final int CUTBOARD_TYPE_SYMBOL_VALUE = 2;
        /**
         * <code>CUTBOARD_TYPE_PLATE = 3;</code>
         */
        public static final int CUTBOARD_TYPE_PLATE_VALUE = 3;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static CutboardType valueOf(int value) {
            return forNumber(value);
        }

        public static CutboardType forNumber(int value) {
            switch (value) {
                case 0:
                    return CUTBOARD_TYPE_UNKNOWN;
                case 1:
                    return CUTBOARD_TYPE_VEHICLE;
                case 2:
                    return CUTBOARD_TYPE_SYMBOL;
                case 3:
                    return CUTBOARD_TYPE_PLATE;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<CutboardType>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                CutboardType> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<CutboardType>() {
                    public CutboardType findValueByNumber(int number) {
                        return CutboardType.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return dg.model.Deepdata.getDescriptor().getEnumTypes().get(0);
        }

        private static final CutboardType[] VALUES = values();

        public static CutboardType valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private CutboardType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:dg.model.CutboardType)
    }

    public interface GenericObjOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dg.model.GenericObj)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .dg.model.ObjType ObjType = 1;</code>
         */
        int getObjTypeValue();

        /**
         * <code>optional .dg.model.ObjType ObjType = 1;</code>
         */
        dg.model.Common.ObjType getObjType();

        /**
         * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
         */
        int getFmtTypeValue();

        /**
         * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
         */
        dg.model.Common.DataFmtType getFmtType();

        /**
         * <code>optional bytes BinData = 3;</code>
         */
        com.google.protobuf.ByteString getBinData();
    }

    /**
     * Protobuf type {@code dg.model.GenericObj}
     */
    public static final class GenericObj extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:dg.model.GenericObj)
            GenericObjOrBuilder {
        // Use GenericObj.newBuilder() to construct.
        private GenericObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private GenericObj() {
            objType_ = 0;
            fmtType_ = 0;
            binData_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private GenericObj(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();

                            objType_ = rawValue;
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();

                            fmtType_ = rawValue;
                            break;
                        }
                        case 26: {

                            binData_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dg.model.Deepdata.internal_static_dg_model_GenericObj_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dg.model.Deepdata.internal_static_dg_model_GenericObj_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dg.model.Deepdata.GenericObj.class, dg.model.Deepdata.GenericObj.Builder.class);
        }

        public static final int OBJTYPE_FIELD_NUMBER = 1;
        private int objType_;

        /**
         * <code>optional .dg.model.ObjType ObjType = 1;</code>
         */
        public int getObjTypeValue() {
            return objType_;
        }

        /**
         * <code>optional .dg.model.ObjType ObjType = 1;</code>
         */
        public dg.model.Common.ObjType getObjType() {
            dg.model.Common.ObjType result = dg.model.Common.ObjType.valueOf(objType_);
            return result == null ? dg.model.Common.ObjType.UNRECOGNIZED : result;
        }

        public static final int FMTTYPE_FIELD_NUMBER = 2;
        private int fmtType_;

        /**
         * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
         */
        public int getFmtTypeValue() {
            return fmtType_;
        }

        /**
         * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
         */
        public dg.model.Common.DataFmtType getFmtType() {
            dg.model.Common.DataFmtType result = dg.model.Common.DataFmtType.valueOf(fmtType_);
            return result == null ? dg.model.Common.DataFmtType.UNRECOGNIZED : result;
        }

        public static final int BINDATA_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString binData_;

        /**
         * <code>optional bytes BinData = 3;</code>
         */
        public com.google.protobuf.ByteString getBinData() {
            return binData_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (objType_ != dg.model.Common.ObjType.OBJ_TYPE_UNKNOWN.getNumber()) {
                output.writeEnum(1, objType_);
            }
            if (fmtType_ != dg.model.Common.DataFmtType.UNKNOWNFMT.getNumber()) {
                output.writeEnum(2, fmtType_);
            }
            if (!binData_.isEmpty()) {
                output.writeBytes(3, binData_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (objType_ != dg.model.Common.ObjType.OBJ_TYPE_UNKNOWN.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, objType_);
            }
            if (fmtType_ != dg.model.Common.DataFmtType.UNKNOWNFMT.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, fmtType_);
            }
            if (!binData_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, binData_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof dg.model.Deepdata.GenericObj)) {
                return super.equals(obj);
            }
            dg.model.Deepdata.GenericObj other = (dg.model.Deepdata.GenericObj) obj;

            boolean result = true;
            result = result && objType_ == other.objType_;
            result = result && fmtType_ == other.fmtType_;
            result = result && getBinData()
                    .equals(other.getBinData());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + OBJTYPE_FIELD_NUMBER;
            hash = (53 * hash) + objType_;
            hash = (37 * hash) + FMTTYPE_FIELD_NUMBER;
            hash = (53 * hash) + fmtType_;
            hash = (37 * hash) + BINDATA_FIELD_NUMBER;
            hash = (53 * hash) + getBinData().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dg.model.Deepdata.GenericObj parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dg.model.Deepdata.GenericObj parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dg.model.Deepdata.GenericObj parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dg.model.Deepdata.GenericObj parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dg.model.Deepdata.GenericObj parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static dg.model.Deepdata.GenericObj parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dg.model.Deepdata.GenericObj parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dg.model.Deepdata.GenericObj parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dg.model.Deepdata.GenericObj parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static dg.model.Deepdata.GenericObj parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(dg.model.Deepdata.GenericObj prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code dg.model.GenericObj}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dg.model.GenericObj)
                dg.model.Deepdata.GenericObjOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dg.model.Deepdata.internal_static_dg_model_GenericObj_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dg.model.Deepdata.internal_static_dg_model_GenericObj_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dg.model.Deepdata.GenericObj.class, dg.model.Deepdata.GenericObj.Builder.class);
            }

            // Construct using dg.model.Deepdata.GenericObj.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                objType_ = 0;

                fmtType_ = 0;

                binData_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dg.model.Deepdata.internal_static_dg_model_GenericObj_descriptor;
            }

            public dg.model.Deepdata.GenericObj getDefaultInstanceForType() {
                return dg.model.Deepdata.GenericObj.getDefaultInstance();
            }

            public dg.model.Deepdata.GenericObj build() {
                dg.model.Deepdata.GenericObj result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public dg.model.Deepdata.GenericObj buildPartial() {
                dg.model.Deepdata.GenericObj result = new dg.model.Deepdata.GenericObj(this);
                result.objType_ = objType_;
                result.fmtType_ = fmtType_;
                result.binData_ = binData_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dg.model.Deepdata.GenericObj) {
                    return mergeFrom((dg.model.Deepdata.GenericObj) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dg.model.Deepdata.GenericObj other) {
                if (other == dg.model.Deepdata.GenericObj.getDefaultInstance()) return this;
                if (other.objType_ != 0) {
                    setObjTypeValue(other.getObjTypeValue());
                }
                if (other.fmtType_ != 0) {
                    setFmtTypeValue(other.getFmtTypeValue());
                }
                if (other.getBinData() != com.google.protobuf.ByteString.EMPTY) {
                    setBinData(other.getBinData());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                dg.model.Deepdata.GenericObj parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (dg.model.Deepdata.GenericObj) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int objType_ = 0;

            /**
             * <code>optional .dg.model.ObjType ObjType = 1;</code>
             */
            public int getObjTypeValue() {
                return objType_;
            }

            /**
             * <code>optional .dg.model.ObjType ObjType = 1;</code>
             */
            public Builder setObjTypeValue(int value) {
                objType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .dg.model.ObjType ObjType = 1;</code>
             */
            public dg.model.Common.ObjType getObjType() {
                dg.model.Common.ObjType result = dg.model.Common.ObjType.valueOf(objType_);
                return result == null ? dg.model.Common.ObjType.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .dg.model.ObjType ObjType = 1;</code>
             */
            public Builder setObjType(dg.model.Common.ObjType value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                objType_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .dg.model.ObjType ObjType = 1;</code>
             */
            public Builder clearObjType() {

                objType_ = 0;
                onChanged();
                return this;
            }

            private int fmtType_ = 0;

            /**
             * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
             */
            public int getFmtTypeValue() {
                return fmtType_;
            }

            /**
             * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
             */
            public Builder setFmtTypeValue(int value) {
                fmtType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
             */
            public dg.model.Common.DataFmtType getFmtType() {
                dg.model.Common.DataFmtType result = dg.model.Common.DataFmtType.valueOf(fmtType_);
                return result == null ? dg.model.Common.DataFmtType.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
             */
            public Builder setFmtType(dg.model.Common.DataFmtType value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                fmtType_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .dg.model.DataFmtType FmtType = 2;</code>
             */
            public Builder clearFmtType() {

                fmtType_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString binData_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes BinData = 3;</code>
             */
            public com.google.protobuf.ByteString getBinData() {
                return binData_;
            }

            /**
             * <code>optional bytes BinData = 3;</code>
             */
            public Builder setBinData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                binData_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes BinData = 3;</code>
             */
            public Builder clearBinData() {

                binData_ = getDefaultInstance().getBinData();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:dg.model.GenericObj)
        }

        // @@protoc_insertion_point(class_scope:dg.model.GenericObj)
        private static final dg.model.Deepdata.GenericObj DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new dg.model.Deepdata.GenericObj();
        }

        public static dg.model.Deepdata.GenericObj getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<GenericObj>
                PARSER = new com.google.protobuf.AbstractParser<GenericObj>() {
            public GenericObj parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new GenericObj(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<GenericObj> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<GenericObj> getParserForType() {
            return PARSER;
        }

        public dg.model.Deepdata.GenericObj getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dg_model_GenericObj_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_dg_model_GenericObj_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016deepdata.proto\022\010dg.model\032\014common.proto" +
                        "\"i\n\nGenericObj\022\"\n\007ObjType\030\001 \001(\0162\021.dg.mod" +
                        "el.ObjType\022&\n\007FmtType\030\002 \001(\0162\025.dg.model.D" +
                        "ataFmtType\022\017\n\007BinData\030\003 \001(\014*w\n\014CutboardT" +
                        "ype\022\031\n\025CUTBOARD_TYPE_UNKNOWN\020\000\022\031\n\025CUTBOA" +
                        "RD_TYPE_VEHICLE\020\001\022\030\n\024CUTBOARD_TYPE_SYMBO" +
                        "L\020\002\022\027\n\023CUTBOARD_TYPE_PLATE\020\003b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                dg.model.Common.getDescriptor(),
                        }, assigner);
        internal_static_dg_model_GenericObj_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dg_model_GenericObj_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_dg_model_GenericObj_descriptor,
                new java.lang.String[]{"ObjType", "FmtType", "BinData",});
        dg.model.Common.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
