/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.netposa.poseidon.face.rpc.outrpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-02-27")
public class AccompanyAyalyzeInputRecord implements org.apache.thrift.TBase<AccompanyAyalyzeInputRecord, AccompanyAyalyzeInputRecord._Fields>, java.io.Serializable, Cloneable, Comparable<AccompanyAyalyzeInputRecord> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AccompanyAyalyzeInputRecord");

  private static final org.apache.thrift.protocol.TField START_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("startTime", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField END_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("endTime", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField FEATURE_FIELD_DESC = new org.apache.thrift.protocol.TField("feature", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField DISTENCE_FIELD_DESC = new org.apache.thrift.protocol.TField("distence", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField ACCOMPANY_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("accompanyCount", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField ACCOMPANY_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("accompanyTime", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField CAMERA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("cameraId", org.apache.thrift.protocol.TType.STRING, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new AccompanyAyalyzeInputRecordStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new AccompanyAyalyzeInputRecordTupleSchemeFactory();

  public long startTime; // required
  public long endTime; // required
  public java.nio.ByteBuffer feature; // required
  public int distence; // required
  public int accompanyCount; // required
  public int accompanyTime; // required
  public java.lang.String cameraId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    START_TIME((short)1, "startTime"),
    END_TIME((short)2, "endTime"),
    FEATURE((short)3, "feature"),
    DISTENCE((short)4, "distence"),
    ACCOMPANY_COUNT((short)5, "accompanyCount"),
    ACCOMPANY_TIME((short)6, "accompanyTime"),
    CAMERA_ID((short)7, "cameraId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // START_TIME
          return START_TIME;
        case 2: // END_TIME
          return END_TIME;
        case 3: // FEATURE
          return FEATURE;
        case 4: // DISTENCE
          return DISTENCE;
        case 5: // ACCOMPANY_COUNT
          return ACCOMPANY_COUNT;
        case 6: // ACCOMPANY_TIME
          return ACCOMPANY_TIME;
        case 7: // CAMERA_ID
          return CAMERA_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STARTTIME_ISSET_ID = 0;
  private static final int __ENDTIME_ISSET_ID = 1;
  private static final int __DISTENCE_ISSET_ID = 2;
  private static final int __ACCOMPANYCOUNT_ISSET_ID = 3;
  private static final int __ACCOMPANYTIME_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.START_TIME, new org.apache.thrift.meta_data.FieldMetaData("startTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.END_TIME, new org.apache.thrift.meta_data.FieldMetaData("endTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FEATURE, new org.apache.thrift.meta_data.FieldMetaData("feature", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.DISTENCE, new org.apache.thrift.meta_data.FieldMetaData("distence", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ACCOMPANY_COUNT, new org.apache.thrift.meta_data.FieldMetaData("accompanyCount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ACCOMPANY_TIME, new org.apache.thrift.meta_data.FieldMetaData("accompanyTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CAMERA_ID, new org.apache.thrift.meta_data.FieldMetaData("cameraId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AccompanyAyalyzeInputRecord.class, metaDataMap);
  }

  public AccompanyAyalyzeInputRecord() {
  }

  public AccompanyAyalyzeInputRecord(
    long startTime,
    long endTime,
    java.nio.ByteBuffer feature,
    int distence,
    int accompanyCount,
    int accompanyTime,
    java.lang.String cameraId)
  {
    this();
    this.startTime = startTime;
    setStartTimeIsSet(true);
    this.endTime = endTime;
    setEndTimeIsSet(true);
    this.feature = org.apache.thrift.TBaseHelper.copyBinary(feature);
    this.distence = distence;
    setDistenceIsSet(true);
    this.accompanyCount = accompanyCount;
    setAccompanyCountIsSet(true);
    this.accompanyTime = accompanyTime;
    setAccompanyTimeIsSet(true);
    this.cameraId = cameraId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AccompanyAyalyzeInputRecord(AccompanyAyalyzeInputRecord other) {
    __isset_bitfield = other.__isset_bitfield;
    this.startTime = other.startTime;
    this.endTime = other.endTime;
    if (other.isSetFeature()) {
      this.feature = org.apache.thrift.TBaseHelper.copyBinary(other.feature);
    }
    this.distence = other.distence;
    this.accompanyCount = other.accompanyCount;
    this.accompanyTime = other.accompanyTime;
    if (other.isSetCameraId()) {
      this.cameraId = other.cameraId;
    }
  }

  public AccompanyAyalyzeInputRecord deepCopy() {
    return new AccompanyAyalyzeInputRecord(this);
  }

  @Override
  public void clear() {
    setStartTimeIsSet(false);
    this.startTime = 0;
    setEndTimeIsSet(false);
    this.endTime = 0;
    this.feature = null;
    setDistenceIsSet(false);
    this.distence = 0;
    setAccompanyCountIsSet(false);
    this.accompanyCount = 0;
    setAccompanyTimeIsSet(false);
    this.accompanyTime = 0;
    this.cameraId = null;
  }

  public long getStartTime() {
    return this.startTime;
  }

  public AccompanyAyalyzeInputRecord setStartTime(long startTime) {
    this.startTime = startTime;
    setStartTimeIsSet(true);
    return this;
  }

  public void unsetStartTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STARTTIME_ISSET_ID);
  }

  /** Returns true if field startTime is set (has been assigned a value) and false otherwise */
  public boolean isSetStartTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STARTTIME_ISSET_ID);
  }

  public void setStartTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STARTTIME_ISSET_ID, value);
  }

  public long getEndTime() {
    return this.endTime;
  }

  public AccompanyAyalyzeInputRecord setEndTime(long endTime) {
    this.endTime = endTime;
    setEndTimeIsSet(true);
    return this;
  }

  public void unsetEndTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENDTIME_ISSET_ID);
  }

  /** Returns true if field endTime is set (has been assigned a value) and false otherwise */
  public boolean isSetEndTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENDTIME_ISSET_ID);
  }

  public void setEndTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENDTIME_ISSET_ID, value);
  }

  public byte[] getFeature() {
    setFeature(org.apache.thrift.TBaseHelper.rightSize(feature));
    return feature == null ? null : feature.array();
  }

  public java.nio.ByteBuffer bufferForFeature() {
    return org.apache.thrift.TBaseHelper.copyBinary(feature);
  }

  public AccompanyAyalyzeInputRecord setFeature(byte[] feature) {
    this.feature = feature == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(feature.clone());
    return this;
  }

  public AccompanyAyalyzeInputRecord setFeature(java.nio.ByteBuffer feature) {
    this.feature = org.apache.thrift.TBaseHelper.copyBinary(feature);
    return this;
  }

  public void unsetFeature() {
    this.feature = null;
  }

  /** Returns true if field feature is set (has been assigned a value) and false otherwise */
  public boolean isSetFeature() {
    return this.feature != null;
  }

  public void setFeatureIsSet(boolean value) {
    if (!value) {
      this.feature = null;
    }
  }

  public int getDistence() {
    return this.distence;
  }

  public AccompanyAyalyzeInputRecord setDistence(int distence) {
    this.distence = distence;
    setDistenceIsSet(true);
    return this;
  }

  public void unsetDistence() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISTENCE_ISSET_ID);
  }

  /** Returns true if field distence is set (has been assigned a value) and false otherwise */
  public boolean isSetDistence() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISTENCE_ISSET_ID);
  }

  public void setDistenceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISTENCE_ISSET_ID, value);
  }

  public int getAccompanyCount() {
    return this.accompanyCount;
  }

  public AccompanyAyalyzeInputRecord setAccompanyCount(int accompanyCount) {
    this.accompanyCount = accompanyCount;
    setAccompanyCountIsSet(true);
    return this;
  }

  public void unsetAccompanyCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ACCOMPANYCOUNT_ISSET_ID);
  }

  /** Returns true if field accompanyCount is set (has been assigned a value) and false otherwise */
  public boolean isSetAccompanyCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ACCOMPANYCOUNT_ISSET_ID);
  }

  public void setAccompanyCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ACCOMPANYCOUNT_ISSET_ID, value);
  }

  public int getAccompanyTime() {
    return this.accompanyTime;
  }

  public AccompanyAyalyzeInputRecord setAccompanyTime(int accompanyTime) {
    this.accompanyTime = accompanyTime;
    setAccompanyTimeIsSet(true);
    return this;
  }

  public void unsetAccompanyTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ACCOMPANYTIME_ISSET_ID);
  }

  /** Returns true if field accompanyTime is set (has been assigned a value) and false otherwise */
  public boolean isSetAccompanyTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ACCOMPANYTIME_ISSET_ID);
  }

  public void setAccompanyTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ACCOMPANYTIME_ISSET_ID, value);
  }

  public java.lang.String getCameraId() {
    return this.cameraId;
  }

  public AccompanyAyalyzeInputRecord setCameraId(java.lang.String cameraId) {
    this.cameraId = cameraId;
    return this;
  }

  public void unsetCameraId() {
    this.cameraId = null;
  }

  /** Returns true if field cameraId is set (has been assigned a value) and false otherwise */
  public boolean isSetCameraId() {
    return this.cameraId != null;
  }

  public void setCameraIdIsSet(boolean value) {
    if (!value) {
      this.cameraId = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case START_TIME:
      if (value == null) {
        unsetStartTime();
      } else {
        setStartTime((java.lang.Long)value);
      }
      break;

    case END_TIME:
      if (value == null) {
        unsetEndTime();
      } else {
        setEndTime((java.lang.Long)value);
      }
      break;

    case FEATURE:
      if (value == null) {
        unsetFeature();
      } else {
        if (value instanceof byte[]) {
          setFeature((byte[])value);
        } else {
          setFeature((java.nio.ByteBuffer)value);
        }
      }
      break;

    case DISTENCE:
      if (value == null) {
        unsetDistence();
      } else {
        setDistence((java.lang.Integer)value);
      }
      break;

    case ACCOMPANY_COUNT:
      if (value == null) {
        unsetAccompanyCount();
      } else {
        setAccompanyCount((java.lang.Integer)value);
      }
      break;

    case ACCOMPANY_TIME:
      if (value == null) {
        unsetAccompanyTime();
      } else {
        setAccompanyTime((java.lang.Integer)value);
      }
      break;

    case CAMERA_ID:
      if (value == null) {
        unsetCameraId();
      } else {
        setCameraId((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case START_TIME:
      return getStartTime();

    case END_TIME:
      return getEndTime();

    case FEATURE:
      return getFeature();

    case DISTENCE:
      return getDistence();

    case ACCOMPANY_COUNT:
      return getAccompanyCount();

    case ACCOMPANY_TIME:
      return getAccompanyTime();

    case CAMERA_ID:
      return getCameraId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case START_TIME:
      return isSetStartTime();
    case END_TIME:
      return isSetEndTime();
    case FEATURE:
      return isSetFeature();
    case DISTENCE:
      return isSetDistence();
    case ACCOMPANY_COUNT:
      return isSetAccompanyCount();
    case ACCOMPANY_TIME:
      return isSetAccompanyTime();
    case CAMERA_ID:
      return isSetCameraId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof AccompanyAyalyzeInputRecord)
      return this.equals((AccompanyAyalyzeInputRecord)that);
    return false;
  }

  public boolean equals(AccompanyAyalyzeInputRecord that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_startTime = true;
    boolean that_present_startTime = true;
    if (this_present_startTime || that_present_startTime) {
      if (!(this_present_startTime && that_present_startTime))
        return false;
      if (this.startTime != that.startTime)
        return false;
    }

    boolean this_present_endTime = true;
    boolean that_present_endTime = true;
    if (this_present_endTime || that_present_endTime) {
      if (!(this_present_endTime && that_present_endTime))
        return false;
      if (this.endTime != that.endTime)
        return false;
    }

    boolean this_present_feature = true && this.isSetFeature();
    boolean that_present_feature = true && that.isSetFeature();
    if (this_present_feature || that_present_feature) {
      if (!(this_present_feature && that_present_feature))
        return false;
      if (!this.feature.equals(that.feature))
        return false;
    }

    boolean this_present_distence = true;
    boolean that_present_distence = true;
    if (this_present_distence || that_present_distence) {
      if (!(this_present_distence && that_present_distence))
        return false;
      if (this.distence != that.distence)
        return false;
    }

    boolean this_present_accompanyCount = true;
    boolean that_present_accompanyCount = true;
    if (this_present_accompanyCount || that_present_accompanyCount) {
      if (!(this_present_accompanyCount && that_present_accompanyCount))
        return false;
      if (this.accompanyCount != that.accompanyCount)
        return false;
    }

    boolean this_present_accompanyTime = true;
    boolean that_present_accompanyTime = true;
    if (this_present_accompanyTime || that_present_accompanyTime) {
      if (!(this_present_accompanyTime && that_present_accompanyTime))
        return false;
      if (this.accompanyTime != that.accompanyTime)
        return false;
    }

    boolean this_present_cameraId = true && this.isSetCameraId();
    boolean that_present_cameraId = true && that.isSetCameraId();
    if (this_present_cameraId || that_present_cameraId) {
      if (!(this_present_cameraId && that_present_cameraId))
        return false;
      if (!this.cameraId.equals(that.cameraId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(startTime);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(endTime);

    hashCode = hashCode * 8191 + ((isSetFeature()) ? 131071 : 524287);
    if (isSetFeature())
      hashCode = hashCode * 8191 + feature.hashCode();

    hashCode = hashCode * 8191 + distence;

    hashCode = hashCode * 8191 + accompanyCount;

    hashCode = hashCode * 8191 + accompanyTime;

    hashCode = hashCode * 8191 + ((isSetCameraId()) ? 131071 : 524287);
    if (isSetCameraId())
      hashCode = hashCode * 8191 + cameraId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(AccompanyAyalyzeInputRecord other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetStartTime()).compareTo(other.isSetStartTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startTime, other.startTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEndTime()).compareTo(other.isSetEndTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endTime, other.endTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFeature()).compareTo(other.isSetFeature());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFeature()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.feature, other.feature);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDistence()).compareTo(other.isSetDistence());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDistence()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.distence, other.distence);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAccompanyCount()).compareTo(other.isSetAccompanyCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccompanyCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accompanyCount, other.accompanyCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAccompanyTime()).compareTo(other.isSetAccompanyTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccompanyTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accompanyTime, other.accompanyTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCameraId()).compareTo(other.isSetCameraId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCameraId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cameraId, other.cameraId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("AccompanyAyalyzeInputRecord(");
    boolean first = true;

    sb.append("startTime:");
    sb.append(this.startTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("endTime:");
    sb.append(this.endTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("feature:");
    if (this.feature == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.feature, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("distence:");
    sb.append(this.distence);
    first = false;
    if (!first) sb.append(", ");
    sb.append("accompanyCount:");
    sb.append(this.accompanyCount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("accompanyTime:");
    sb.append(this.accompanyTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("cameraId:");
    if (this.cameraId == null) {
      sb.append("null");
    } else {
      sb.append(this.cameraId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AccompanyAyalyzeInputRecordStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AccompanyAyalyzeInputRecordStandardScheme getScheme() {
      return new AccompanyAyalyzeInputRecordStandardScheme();
    }
  }

  private static class AccompanyAyalyzeInputRecordStandardScheme extends org.apache.thrift.scheme.StandardScheme<AccompanyAyalyzeInputRecord> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AccompanyAyalyzeInputRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // START_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startTime = iprot.readI64();
              struct.setStartTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // END_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endTime = iprot.readI64();
              struct.setEndTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FEATURE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.feature = iprot.readBinary();
              struct.setFeatureIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // DISTENCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.distence = iprot.readI32();
              struct.setDistenceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ACCOMPANY_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.accompanyCount = iprot.readI32();
              struct.setAccompanyCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ACCOMPANY_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.accompanyTime = iprot.readI32();
              struct.setAccompanyTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CAMERA_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cameraId = iprot.readString();
              struct.setCameraIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AccompanyAyalyzeInputRecord struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(START_TIME_FIELD_DESC);
      oprot.writeI64(struct.startTime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(END_TIME_FIELD_DESC);
      oprot.writeI64(struct.endTime);
      oprot.writeFieldEnd();
      if (struct.feature != null) {
        oprot.writeFieldBegin(FEATURE_FIELD_DESC);
        oprot.writeBinary(struct.feature);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DISTENCE_FIELD_DESC);
      oprot.writeI32(struct.distence);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ACCOMPANY_COUNT_FIELD_DESC);
      oprot.writeI32(struct.accompanyCount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ACCOMPANY_TIME_FIELD_DESC);
      oprot.writeI32(struct.accompanyTime);
      oprot.writeFieldEnd();
      if (struct.cameraId != null) {
        oprot.writeFieldBegin(CAMERA_ID_FIELD_DESC);
        oprot.writeString(struct.cameraId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AccompanyAyalyzeInputRecordTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AccompanyAyalyzeInputRecordTupleScheme getScheme() {
      return new AccompanyAyalyzeInputRecordTupleScheme();
    }
  }

  private static class AccompanyAyalyzeInputRecordTupleScheme extends org.apache.thrift.scheme.TupleScheme<AccompanyAyalyzeInputRecord> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AccompanyAyalyzeInputRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetStartTime()) {
        optionals.set(0);
      }
      if (struct.isSetEndTime()) {
        optionals.set(1);
      }
      if (struct.isSetFeature()) {
        optionals.set(2);
      }
      if (struct.isSetDistence()) {
        optionals.set(3);
      }
      if (struct.isSetAccompanyCount()) {
        optionals.set(4);
      }
      if (struct.isSetAccompanyTime()) {
        optionals.set(5);
      }
      if (struct.isSetCameraId()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetStartTime()) {
        oprot.writeI64(struct.startTime);
      }
      if (struct.isSetEndTime()) {
        oprot.writeI64(struct.endTime);
      }
      if (struct.isSetFeature()) {
        oprot.writeBinary(struct.feature);
      }
      if (struct.isSetDistence()) {
        oprot.writeI32(struct.distence);
      }
      if (struct.isSetAccompanyCount()) {
        oprot.writeI32(struct.accompanyCount);
      }
      if (struct.isSetAccompanyTime()) {
        oprot.writeI32(struct.accompanyTime);
      }
      if (struct.isSetCameraId()) {
        oprot.writeString(struct.cameraId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AccompanyAyalyzeInputRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.startTime = iprot.readI64();
        struct.setStartTimeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.endTime = iprot.readI64();
        struct.setEndTimeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.feature = iprot.readBinary();
        struct.setFeatureIsSet(true);
      }
      if (incoming.get(3)) {
        struct.distence = iprot.readI32();
        struct.setDistenceIsSet(true);
      }
      if (incoming.get(4)) {
        struct.accompanyCount = iprot.readI32();
        struct.setAccompanyCountIsSet(true);
      }
      if (incoming.get(5)) {
        struct.accompanyTime = iprot.readI32();
        struct.setAccompanyTimeIsSet(true);
      }
      if (incoming.get(6)) {
        struct.cameraId = iprot.readString();
        struct.setCameraIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

