/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.netposa.poseidon.face.rpc.outrpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 人脸日志编号查特征输入
 * 
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-02-27")
public class SearchFeatureByLogInputRecord implements org.apache.thrift.TBase<SearchFeatureByLogInputRecord, SearchFeatureByLogInputRecord._Fields>, java.io.Serializable, Cloneable, Comparable<SearchFeatureByLogInputRecord> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SearchFeatureByLogInputRecord");

  private static final org.apache.thrift.protocol.TField LOG_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("logNum", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField GATHER_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("gatherTime", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SearchFeatureByLogInputRecordStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SearchFeatureByLogInputRecordTupleSchemeFactory();

  public java.lang.String logNum; // required
  public long gatherTime; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOG_NUM((short)1, "logNum"),
    GATHER_TIME((short)2, "gatherTime");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOG_NUM
          return LOG_NUM;
        case 2: // GATHER_TIME
          return GATHER_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __GATHERTIME_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOG_NUM, new org.apache.thrift.meta_data.FieldMetaData("logNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GATHER_TIME, new org.apache.thrift.meta_data.FieldMetaData("gatherTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SearchFeatureByLogInputRecord.class, metaDataMap);
  }

  public SearchFeatureByLogInputRecord() {
  }

  public SearchFeatureByLogInputRecord(
    java.lang.String logNum,
    long gatherTime)
  {
    this();
    this.logNum = logNum;
    this.gatherTime = gatherTime;
    setGatherTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SearchFeatureByLogInputRecord(SearchFeatureByLogInputRecord other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLogNum()) {
      this.logNum = other.logNum;
    }
    this.gatherTime = other.gatherTime;
  }

  public SearchFeatureByLogInputRecord deepCopy() {
    return new SearchFeatureByLogInputRecord(this);
  }

  @Override
  public void clear() {
    this.logNum = null;
    setGatherTimeIsSet(false);
    this.gatherTime = 0;
  }

  public java.lang.String getLogNum() {
    return this.logNum;
  }

  public SearchFeatureByLogInputRecord setLogNum(java.lang.String logNum) {
    this.logNum = logNum;
    return this;
  }

  public void unsetLogNum() {
    this.logNum = null;
  }

  /** Returns true if field logNum is set (has been assigned a value) and false otherwise */
  public boolean isSetLogNum() {
    return this.logNum != null;
  }

  public void setLogNumIsSet(boolean value) {
    if (!value) {
      this.logNum = null;
    }
  }

  public long getGatherTime() {
    return this.gatherTime;
  }

  public SearchFeatureByLogInputRecord setGatherTime(long gatherTime) {
    this.gatherTime = gatherTime;
    setGatherTimeIsSet(true);
    return this;
  }

  public void unsetGatherTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __GATHERTIME_ISSET_ID);
  }

  /** Returns true if field gatherTime is set (has been assigned a value) and false otherwise */
  public boolean isSetGatherTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __GATHERTIME_ISSET_ID);
  }

  public void setGatherTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __GATHERTIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case LOG_NUM:
      if (value == null) {
        unsetLogNum();
      } else {
        setLogNum((java.lang.String)value);
      }
      break;

    case GATHER_TIME:
      if (value == null) {
        unsetGatherTime();
      } else {
        setGatherTime((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LOG_NUM:
      return getLogNum();

    case GATHER_TIME:
      return getGatherTime();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LOG_NUM:
      return isSetLogNum();
    case GATHER_TIME:
      return isSetGatherTime();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SearchFeatureByLogInputRecord)
      return this.equals((SearchFeatureByLogInputRecord)that);
    return false;
  }

  public boolean equals(SearchFeatureByLogInputRecord that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_logNum = true && this.isSetLogNum();
    boolean that_present_logNum = true && that.isSetLogNum();
    if (this_present_logNum || that_present_logNum) {
      if (!(this_present_logNum && that_present_logNum))
        return false;
      if (!this.logNum.equals(that.logNum))
        return false;
    }

    boolean this_present_gatherTime = true;
    boolean that_present_gatherTime = true;
    if (this_present_gatherTime || that_present_gatherTime) {
      if (!(this_present_gatherTime && that_present_gatherTime))
        return false;
      if (this.gatherTime != that.gatherTime)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetLogNum()) ? 131071 : 524287);
    if (isSetLogNum())
      hashCode = hashCode * 8191 + logNum.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(gatherTime);

    return hashCode;
  }

  @Override
  public int compareTo(SearchFeatureByLogInputRecord other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetLogNum()).compareTo(other.isSetLogNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLogNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.logNum, other.logNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGatherTime()).compareTo(other.isSetGatherTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGatherTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gatherTime, other.gatherTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SearchFeatureByLogInputRecord(");
    boolean first = true;

    sb.append("logNum:");
    if (this.logNum == null) {
      sb.append("null");
    } else {
      sb.append(this.logNum);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("gatherTime:");
    sb.append(this.gatherTime);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SearchFeatureByLogInputRecordStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SearchFeatureByLogInputRecordStandardScheme getScheme() {
      return new SearchFeatureByLogInputRecordStandardScheme();
    }
  }

  private static class SearchFeatureByLogInputRecordStandardScheme extends org.apache.thrift.scheme.StandardScheme<SearchFeatureByLogInputRecord> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SearchFeatureByLogInputRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LOG_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.logNum = iprot.readString();
              struct.setLogNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // GATHER_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.gatherTime = iprot.readI64();
              struct.setGatherTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SearchFeatureByLogInputRecord struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.logNum != null) {
        oprot.writeFieldBegin(LOG_NUM_FIELD_DESC);
        oprot.writeString(struct.logNum);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(GATHER_TIME_FIELD_DESC);
      oprot.writeI64(struct.gatherTime);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SearchFeatureByLogInputRecordTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SearchFeatureByLogInputRecordTupleScheme getScheme() {
      return new SearchFeatureByLogInputRecordTupleScheme();
    }
  }

  private static class SearchFeatureByLogInputRecordTupleScheme extends org.apache.thrift.scheme.TupleScheme<SearchFeatureByLogInputRecord> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SearchFeatureByLogInputRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLogNum()) {
        optionals.set(0);
      }
      if (struct.isSetGatherTime()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetLogNum()) {
        oprot.writeString(struct.logNum);
      }
      if (struct.isSetGatherTime()) {
        oprot.writeI64(struct.gatherTime);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SearchFeatureByLogInputRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.logNum = iprot.readString();
        struct.setLogNumIsSet(true);
      }
      if (incoming.get(1)) {
        struct.gatherTime = iprot.readI64();
        struct.setGatherTimeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

