// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicleAllInfo.proto

package com.netposa.poseidon.fakecardetect.utils;

public final class VehicleAllInfo {
  private VehicleAllInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface vehicleAllInfoMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes jlbh = 1;
    /**
     * <code>required bytes jlbh = 1;</code>
     */
    boolean hasJlbh();
    /**
     * <code>required bytes jlbh = 1;</code>
     */
    com.google.protobuf.ByteString getJlbh();

    // required bytes yssj = 2;
    /**
     * <code>required bytes yssj = 2;</code>
     */
    boolean hasYssj();
    /**
     * <code>required bytes yssj = 2;</code>
     */
    com.google.protobuf.ByteString getYssj();

    // required bytes rcg = 3;
    /**
     * <code>required bytes rcg = 3;</code>
     */
    boolean hasRcg();
    /**
     * <code>required bytes rcg = 3;</code>
     */
    com.google.protobuf.ByteString getRcg();

    // required bytes sjly = 4;
    /**
     * <code>required bytes sjly = 4;</code>
     */
    boolean hasSjly();
    /**
     * <code>required bytes sjly = 4;</code>
     */
    com.google.protobuf.ByteString getSjly();
  }
  /**
   * Protobuf type {@code netposa.access.bean.proto.vehicleAllInfoMsg}
   */
  public static final class vehicleAllInfoMsg extends
      com.google.protobuf.GeneratedMessage
      implements vehicleAllInfoMsgOrBuilder {
    // Use vehicleAllInfoMsg.newBuilder() to construct.
    private vehicleAllInfoMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private vehicleAllInfoMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final vehicleAllInfoMsg defaultInstance;
    public static vehicleAllInfoMsg getDefaultInstance() {
      return defaultInstance;
    }

    public vehicleAllInfoMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private vehicleAllInfoMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              jlbh_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              yssj_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              rcg_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              sjly_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VehicleAllInfo.internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VehicleAllInfo.internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vehicleAllInfoMsg.class, Builder.class);
    }

    public static com.google.protobuf.Parser<vehicleAllInfoMsg> PARSER =
        new com.google.protobuf.AbstractParser<vehicleAllInfoMsg>() {
      public vehicleAllInfoMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new vehicleAllInfoMsg(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<vehicleAllInfoMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes jlbh = 1;
    public static final int JLBH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString jlbh_;
    /**
     * <code>required bytes jlbh = 1;</code>
     */
    public boolean hasJlbh() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes jlbh = 1;</code>
     */
    public com.google.protobuf.ByteString getJlbh() {
      return jlbh_;
    }

    // required bytes yssj = 2;
    public static final int YSSJ_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString yssj_;
    /**
     * <code>required bytes yssj = 2;</code>
     */
    public boolean hasYssj() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes yssj = 2;</code>
     */
    public com.google.protobuf.ByteString getYssj() {
      return yssj_;
    }

    // required bytes rcg = 3;
    public static final int RCG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString rcg_;
    /**
     * <code>required bytes rcg = 3;</code>
     */
    public boolean hasRcg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes rcg = 3;</code>
     */
    public com.google.protobuf.ByteString getRcg() {
      return rcg_;
    }

    // required bytes sjly = 4;
    public static final int SJLY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString sjly_;
    /**
     * <code>required bytes sjly = 4;</code>
     */
    public boolean hasSjly() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes sjly = 4;</code>
     */
    public com.google.protobuf.ByteString getSjly() {
      return sjly_;
    }

    private void initFields() {
      jlbh_ = com.google.protobuf.ByteString.EMPTY;
      yssj_ = com.google.protobuf.ByteString.EMPTY;
      rcg_ = com.google.protobuf.ByteString.EMPTY;
      sjly_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasJlbh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYssj()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRcg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSjly()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, jlbh_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, yssj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, rcg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, sjly_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, jlbh_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, yssj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, rcg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, sjly_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static vehicleAllInfoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vehicleAllInfoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vehicleAllInfoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vehicleAllInfoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vehicleAllInfoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vehicleAllInfoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static vehicleAllInfoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static vehicleAllInfoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static vehicleAllInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vehicleAllInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vehicleAllInfoMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netposa.access.bean.proto.vehicleAllInfoMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements vehicleAllInfoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VehicleAllInfo.internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VehicleAllInfo.internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vehicleAllInfoMsg.class, Builder.class);
      }

      // Construct using com.netposa.poseidon.fakecardetect.utils.VehicleAllInfo.vehicleAllInfoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        jlbh_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        yssj_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        rcg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        sjly_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VehicleAllInfo.internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_descriptor;
      }

      public vehicleAllInfoMsg getDefaultInstanceForType() {
        return vehicleAllInfoMsg.getDefaultInstance();
      }

      public vehicleAllInfoMsg build() {
        vehicleAllInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vehicleAllInfoMsg buildPartial() {
        vehicleAllInfoMsg result = new vehicleAllInfoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jlbh_ = jlbh_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.yssj_ = yssj_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rcg_ = rcg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sjly_ = sjly_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vehicleAllInfoMsg) {
          return mergeFrom((vehicleAllInfoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vehicleAllInfoMsg other) {
        if (other == vehicleAllInfoMsg.getDefaultInstance()) return this;
        if (other.hasJlbh()) {
          setJlbh(other.getJlbh());
        }
        if (other.hasYssj()) {
          setYssj(other.getYssj());
        }
        if (other.hasRcg()) {
          setRcg(other.getRcg());
        }
        if (other.hasSjly()) {
          setSjly(other.getSjly());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJlbh()) {

          return false;
        }
        if (!hasYssj()) {

          return false;
        }
        if (!hasRcg()) {

          return false;
        }
        if (!hasSjly()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vehicleAllInfoMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vehicleAllInfoMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes jlbh = 1;
      private com.google.protobuf.ByteString jlbh_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes jlbh = 1;</code>
       */
      public boolean hasJlbh() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes jlbh = 1;</code>
       */
      public com.google.protobuf.ByteString getJlbh() {
        return jlbh_;
      }
      /**
       * <code>required bytes jlbh = 1;</code>
       */
      public Builder setJlbh(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jlbh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes jlbh = 1;</code>
       */
      public Builder clearJlbh() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jlbh_ = getDefaultInstance().getJlbh();
        onChanged();
        return this;
      }

      // required bytes yssj = 2;
      private com.google.protobuf.ByteString yssj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes yssj = 2;</code>
       */
      public boolean hasYssj() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes yssj = 2;</code>
       */
      public com.google.protobuf.ByteString getYssj() {
        return yssj_;
      }
      /**
       * <code>required bytes yssj = 2;</code>
       */
      public Builder setYssj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        yssj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes yssj = 2;</code>
       */
      public Builder clearYssj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        yssj_ = getDefaultInstance().getYssj();
        onChanged();
        return this;
      }

      // required bytes rcg = 3;
      private com.google.protobuf.ByteString rcg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes rcg = 3;</code>
       */
      public boolean hasRcg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes rcg = 3;</code>
       */
      public com.google.protobuf.ByteString getRcg() {
        return rcg_;
      }
      /**
       * <code>required bytes rcg = 3;</code>
       */
      public Builder setRcg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        rcg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes rcg = 3;</code>
       */
      public Builder clearRcg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rcg_ = getDefaultInstance().getRcg();
        onChanged();
        return this;
      }

      // required bytes sjly = 4;
      private com.google.protobuf.ByteString sjly_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes sjly = 4;</code>
       */
      public boolean hasSjly() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes sjly = 4;</code>
       */
      public com.google.protobuf.ByteString getSjly() {
        return sjly_;
      }
      /**
       * <code>required bytes sjly = 4;</code>
       */
      public Builder setSjly(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sjly_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes sjly = 4;</code>
       */
      public Builder clearSjly() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sjly_ = getDefaultInstance().getSjly();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netposa.access.bean.proto.vehicleAllInfoMsg)
    }

    static {
      defaultInstance = new vehicleAllInfoMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netposa.access.bean.proto.vehicleAllInfoMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024vehicleAllInfo.proto\022\031netposa.access.b" +
      "ean.proto\"J\n\021vehicleAllInfoMsg\022\014\n\004jlbh\030\001" +
      " \002(\014\022\014\n\004yssj\030\002 \002(\014\022\013\n\003rcg\030\003 \002(\014\022\014\n\004sjly\030" +
      "\004 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netposa_access_bean_proto_vehicleAllInfoMsg_descriptor,
              new String[] { "Jlbh", "Yssj", "Rcg", "Sjly", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
