/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.netposa.poseidon.human.rpc.inrpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 热数据数据结构
 * 
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-02-05")
public class RecentDataBean implements org.apache.thrift.TBase<RecentDataBean, RecentDataBean._Fields>, java.io.Serializable, Cloneable, Comparable<RecentDataBean> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RecentDataBean");

  private static final org.apache.thrift.protocol.TField LOG_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("logNum", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CAMERA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("cameraId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField GATHER_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("gatherTime", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField FEATURE_FIELD_DESC = new org.apache.thrift.protocol.TField("feature", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RecentDataBeanStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RecentDataBeanTupleSchemeFactory();

  public java.lang.String logNum; // required
  public java.lang.String cameraId; // required
  public long gatherTime; // required
  public java.util.List<java.lang.Double> feature; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOG_NUM((short)1, "logNum"),
    CAMERA_ID((short)2, "cameraId"),
    GATHER_TIME((short)3, "gatherTime"),
    FEATURE((short)4, "feature");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOG_NUM
          return LOG_NUM;
        case 2: // CAMERA_ID
          return CAMERA_ID;
        case 3: // GATHER_TIME
          return GATHER_TIME;
        case 4: // FEATURE
          return FEATURE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __GATHERTIME_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOG_NUM, new org.apache.thrift.meta_data.FieldMetaData("logNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CAMERA_ID, new org.apache.thrift.meta_data.FieldMetaData("cameraId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GATHER_TIME, new org.apache.thrift.meta_data.FieldMetaData("gatherTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FEATURE, new org.apache.thrift.meta_data.FieldMetaData("feature", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RecentDataBean.class, metaDataMap);
  }

  public RecentDataBean() {
  }

  public RecentDataBean(
    java.lang.String logNum,
    java.lang.String cameraId,
    long gatherTime,
    java.util.List<java.lang.Double> feature)
  {
    this();
    this.logNum = logNum;
    this.cameraId = cameraId;
    this.gatherTime = gatherTime;
    setGatherTimeIsSet(true);
    this.feature = feature;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RecentDataBean(RecentDataBean other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLogNum()) {
      this.logNum = other.logNum;
    }
    if (other.isSetCameraId()) {
      this.cameraId = other.cameraId;
    }
    this.gatherTime = other.gatherTime;
    if (other.isSetFeature()) {
      java.util.List<java.lang.Double> __this__feature = new java.util.ArrayList<java.lang.Double>(other.feature);
      this.feature = __this__feature;
    }
  }

  public RecentDataBean deepCopy() {
    return new RecentDataBean(this);
  }

  @Override
  public void clear() {
    this.logNum = null;
    this.cameraId = null;
    setGatherTimeIsSet(false);
    this.gatherTime = 0;
    this.feature = null;
  }

  public java.lang.String getLogNum() {
    return this.logNum;
  }

  public RecentDataBean setLogNum(java.lang.String logNum) {
    this.logNum = logNum;
    return this;
  }

  public void unsetLogNum() {
    this.logNum = null;
  }

  /** Returns true if field logNum is set (has been assigned a value) and false otherwise */
  public boolean isSetLogNum() {
    return this.logNum != null;
  }

  public void setLogNumIsSet(boolean value) {
    if (!value) {
      this.logNum = null;
    }
  }

  public java.lang.String getCameraId() {
    return this.cameraId;
  }

  public RecentDataBean setCameraId(java.lang.String cameraId) {
    this.cameraId = cameraId;
    return this;
  }

  public void unsetCameraId() {
    this.cameraId = null;
  }

  /** Returns true if field cameraId is set (has been assigned a value) and false otherwise */
  public boolean isSetCameraId() {
    return this.cameraId != null;
  }

  public void setCameraIdIsSet(boolean value) {
    if (!value) {
      this.cameraId = null;
    }
  }

  public long getGatherTime() {
    return this.gatherTime;
  }

  public RecentDataBean setGatherTime(long gatherTime) {
    this.gatherTime = gatherTime;
    setGatherTimeIsSet(true);
    return this;
  }

  public void unsetGatherTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __GATHERTIME_ISSET_ID);
  }

  /** Returns true if field gatherTime is set (has been assigned a value) and false otherwise */
  public boolean isSetGatherTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __GATHERTIME_ISSET_ID);
  }

  public void setGatherTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __GATHERTIME_ISSET_ID, value);
  }

  public int getFeatureSize() {
    return (this.feature == null) ? 0 : this.feature.size();
  }

  public java.util.Iterator<java.lang.Double> getFeatureIterator() {
    return (this.feature == null) ? null : this.feature.iterator();
  }

  public void addToFeature(double elem) {
    if (this.feature == null) {
      this.feature = new java.util.ArrayList<java.lang.Double>();
    }
    this.feature.add(elem);
  }

  public java.util.List<java.lang.Double> getFeature() {
    return this.feature;
  }

  public RecentDataBean setFeature(java.util.List<java.lang.Double> feature) {
    this.feature = feature;
    return this;
  }

  public void unsetFeature() {
    this.feature = null;
  }

  /** Returns true if field feature is set (has been assigned a value) and false otherwise */
  public boolean isSetFeature() {
    return this.feature != null;
  }

  public void setFeatureIsSet(boolean value) {
    if (!value) {
      this.feature = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case LOG_NUM:
      if (value == null) {
        unsetLogNum();
      } else {
        setLogNum((java.lang.String)value);
      }
      break;

    case CAMERA_ID:
      if (value == null) {
        unsetCameraId();
      } else {
        setCameraId((java.lang.String)value);
      }
      break;

    case GATHER_TIME:
      if (value == null) {
        unsetGatherTime();
      } else {
        setGatherTime((java.lang.Long)value);
      }
      break;

    case FEATURE:
      if (value == null) {
        unsetFeature();
      } else {
        setFeature((java.util.List<java.lang.Double>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LOG_NUM:
      return getLogNum();

    case CAMERA_ID:
      return getCameraId();

    case GATHER_TIME:
      return getGatherTime();

    case FEATURE:
      return getFeature();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LOG_NUM:
      return isSetLogNum();
    case CAMERA_ID:
      return isSetCameraId();
    case GATHER_TIME:
      return isSetGatherTime();
    case FEATURE:
      return isSetFeature();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RecentDataBean)
      return this.equals((RecentDataBean)that);
    return false;
  }

  public boolean equals(RecentDataBean that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_logNum = true && this.isSetLogNum();
    boolean that_present_logNum = true && that.isSetLogNum();
    if (this_present_logNum || that_present_logNum) {
      if (!(this_present_logNum && that_present_logNum))
        return false;
      if (!this.logNum.equals(that.logNum))
        return false;
    }

    boolean this_present_cameraId = true && this.isSetCameraId();
    boolean that_present_cameraId = true && that.isSetCameraId();
    if (this_present_cameraId || that_present_cameraId) {
      if (!(this_present_cameraId && that_present_cameraId))
        return false;
      if (!this.cameraId.equals(that.cameraId))
        return false;
    }

    boolean this_present_gatherTime = true;
    boolean that_present_gatherTime = true;
    if (this_present_gatherTime || that_present_gatherTime) {
      if (!(this_present_gatherTime && that_present_gatherTime))
        return false;
      if (this.gatherTime != that.gatherTime)
        return false;
    }

    boolean this_present_feature = true && this.isSetFeature();
    boolean that_present_feature = true && that.isSetFeature();
    if (this_present_feature || that_present_feature) {
      if (!(this_present_feature && that_present_feature))
        return false;
      if (!this.feature.equals(that.feature))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetLogNum()) ? 131071 : 524287);
    if (isSetLogNum())
      hashCode = hashCode * 8191 + logNum.hashCode();

    hashCode = hashCode * 8191 + ((isSetCameraId()) ? 131071 : 524287);
    if (isSetCameraId())
      hashCode = hashCode * 8191 + cameraId.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(gatherTime);

    hashCode = hashCode * 8191 + ((isSetFeature()) ? 131071 : 524287);
    if (isSetFeature())
      hashCode = hashCode * 8191 + feature.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RecentDataBean other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetLogNum()).compareTo(other.isSetLogNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLogNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.logNum, other.logNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCameraId()).compareTo(other.isSetCameraId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCameraId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cameraId, other.cameraId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGatherTime()).compareTo(other.isSetGatherTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGatherTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gatherTime, other.gatherTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFeature()).compareTo(other.isSetFeature());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFeature()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.feature, other.feature);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RecentDataBean(");
    boolean first = true;

    sb.append("logNum:");
    if (this.logNum == null) {
      sb.append("null");
    } else {
      sb.append(this.logNum);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cameraId:");
    if (this.cameraId == null) {
      sb.append("null");
    } else {
      sb.append(this.cameraId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("gatherTime:");
    sb.append(this.gatherTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("feature:");
    if (this.feature == null) {
      sb.append("null");
    } else {
      sb.append(this.feature);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RecentDataBeanStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RecentDataBeanStandardScheme getScheme() {
      return new RecentDataBeanStandardScheme();
    }
  }

  private static class RecentDataBeanStandardScheme extends org.apache.thrift.scheme.StandardScheme<RecentDataBean> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RecentDataBean struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LOG_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.logNum = iprot.readString();
              struct.setLogNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CAMERA_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cameraId = iprot.readString();
              struct.setCameraIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // GATHER_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.gatherTime = iprot.readI64();
              struct.setGatherTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // FEATURE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.feature = new java.util.ArrayList<java.lang.Double>(_list16.size);
                double _elem17;
                for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                {
                  _elem17 = iprot.readDouble();
                  struct.feature.add(_elem17);
                }
                iprot.readListEnd();
              }
              struct.setFeatureIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RecentDataBean struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.logNum != null) {
        oprot.writeFieldBegin(LOG_NUM_FIELD_DESC);
        oprot.writeString(struct.logNum);
        oprot.writeFieldEnd();
      }
      if (struct.cameraId != null) {
        oprot.writeFieldBegin(CAMERA_ID_FIELD_DESC);
        oprot.writeString(struct.cameraId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(GATHER_TIME_FIELD_DESC);
      oprot.writeI64(struct.gatherTime);
      oprot.writeFieldEnd();
      if (struct.feature != null) {
        oprot.writeFieldBegin(FEATURE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.feature.size()));
          for (double _iter19 : struct.feature)
          {
            oprot.writeDouble(_iter19);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RecentDataBeanTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RecentDataBeanTupleScheme getScheme() {
      return new RecentDataBeanTupleScheme();
    }
  }

  private static class RecentDataBeanTupleScheme extends org.apache.thrift.scheme.TupleScheme<RecentDataBean> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RecentDataBean struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLogNum()) {
        optionals.set(0);
      }
      if (struct.isSetCameraId()) {
        optionals.set(1);
      }
      if (struct.isSetGatherTime()) {
        optionals.set(2);
      }
      if (struct.isSetFeature()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetLogNum()) {
        oprot.writeString(struct.logNum);
      }
      if (struct.isSetCameraId()) {
        oprot.writeString(struct.cameraId);
      }
      if (struct.isSetGatherTime()) {
        oprot.writeI64(struct.gatherTime);
      }
      if (struct.isSetFeature()) {
        {
          oprot.writeI32(struct.feature.size());
          for (double _iter20 : struct.feature)
          {
            oprot.writeDouble(_iter20);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RecentDataBean struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.logNum = iprot.readString();
        struct.setLogNumIsSet(true);
      }
      if (incoming.get(1)) {
        struct.cameraId = iprot.readString();
        struct.setCameraIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.gatherTime = iprot.readI64();
        struct.setGatherTimeIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.feature = new java.util.ArrayList<java.lang.Double>(_list21.size);
          double _elem22;
          for (int _i23 = 0; _i23 < _list21.size; ++_i23)
          {
            _elem22 = iprot.readDouble();
            struct.feature.add(_elem22);
          }
        }
        struct.setFeatureIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

